### ISSUE TITLE
合并进度

### ISSUE THREAD

**Issue by ForeverCarousel** [ColdPaleLight/multiple_flutters#1]
您好，打扰了 没有找到其他地方可以联系到您，麻烦问下您这个engine group 启动透传格式化参数的进度如何呀 是会在未来的版本中增加demo中的接口吗

**Comment by ColdPaleLight** [comment]
> 您好，打扰了 没有找到其他地方可以联系到您，麻烦问下您这个engine group 启动透传格式化参数的进度如何呀 是会在未来的版本中增加demo中的接口吗

你可以把你的微信号发到我的邮箱 coldpalelight@gmail.com，我们通过微信联系
